# Generated by Django 3.2.14 on 2022-09-06 09:39
from django.db import migrations
from django.db import connection


def forward_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE mdm.applicant ADD test varchar NULL;
        """)


def reverse_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
                ALTER TABLE mdm.applicant DROP COLUMN test;
        """)


class Migration(migrations.Migration):

    dependencies = ""

    operations = [ migrations.RunPython(forward_func, reverse_func)]

    