# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2022-12-21 08:51
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection

def forward_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE mdm.unitspace (
                unitspace_id uuid NOT NULL DEFAULT public.uuid_generate_v4(),
                customer_id uuid NOT NULL,
                community_id uuid NOT NULL,
                external_id varchar NULL,
                unit_id uuid NOT NULL,
                unitspace_number varchar NULL,
                space_configuration varchar NULL,
                is_deleted bool DEFAULT false,
                created_date timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_date timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT unitspace_id_pk PRIMARY KEY (unitspace_id),
                CONSTRAINT unitspace_fk FOREIGN KEY (unit_id) REFERENCES mdm.unit(unit_id) ON DELETE CASCADE ON UPDATE CASCADE
            );
        """)


def reverse_func(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
                alter table mdm.lease 
                    add COLUMN IF NOT EXISTS unitspace_id uuid null,
                    add COLUMN IF NOT EXISTS unitspace_number varchar null;
            ALTER TABLE mdm.lease DROP CONSTRAINT IF EXISTS lease_fk;
            alter table mdm.lease add constraint lease_fk foreign key (unitspace_id) references mdm.unitspace(unitspace_id) on
            delete
                cascade on
                    update
                    cascade;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('SyncService', '0001_mdm'),
    ]

    operations = [migrations.RunPython(forward_func, reverse_func)]

