HOST = "https://nestiolistings.com"
AVAILABLE_TIMES_PATH = "/api/v2/appointments/group/{group_id}/available-times/?from_date={from_date}&to_date={to_date}"
TOUR_PATH = "/api/v2/appointments/group/{group_id}/book/"
GUEST_CARD_PATH = "/api/v2/clients/"
FUNNEL_API_KEY = "FUNNEL_API_KEY"
DESIRED_BEDS = "desiredBeds"
GUEST = "guest"
GUEST_PREFERENCE = "guestPreference"
FIRST_NAME = "first_name"
LAST_NAME = "last_name"
EMAIL = "email"
PHONE = "phone"
MOVE_IN_DATE = "moveInDate"
DESIRED_RENT = "desiredRent"
DESIRED_BATHS = "desiredBaths"
MOVE_REASON = "moveInReason"
PREFERRED_AMENITIES = "preferredAmenities"
CLIENT = "client"
START = "start"
ID = "id"
APPOINTMENT = "appointment"
ERRORS = "errors"
GROUP_ID = "group_id"
LEAD_SOURCE ="lead_source"
MESSAGE = "message"
DATA = "data"
GUEST_COMMENT = "guestComment"
DIGITAL_HUMAN = "digital human"
WEBSITE = "website"
GUIDED = "guided"


