HTTP_OK_CODE=200
HTTP_BAD_REQUEST_CODE=400
HTTP_NOT_FOUND_CODE=404
HTTP_SERVER_ERROR=500
HTTP_METHOD_NOT_ALLOWED=405
HTTP_SERVER_ERROR_MSJ="Third parther server returns a time-out"
HTTP_NOT_FOUND_MSJ="The email was not found"
OUTGOING_POST='[Resman] Post Lead Management 4_0'
OUTGOING_GET='[Resman] Search Prospects'
ENVIRON='wsgi_environ'
GET_QUERY_PARAMS='zato.http.GET'
POST_QUERY_PARAMS='zato.http.POST'
PATCH_QUERY_PARAMS='zato.http.PATCH'
ALL_PATH_PARAMS='zato.http.path_params'
RESMAN="ResMan"
STATUS="Status"
ERROR_DESCRIPTION="ErrorDescription"
RESPONSE="Response"
LEADMANAGEMENT="LeadManagement"
PROSPECTS="Prospects"