import collections


class FormFieldMap:
    def __init__(self):
        self.__quextMapping = BiDirectionMap(quext_to_bluemoon)

    def getquextfield(self, key):
        return self.__quextMapping.inverse[key]

    def getbluemoonfield(self, key):
        return self.__quextMapping[key]

    def setquextfield(self, key, value):
        self.__quextMapping[key] = value

    def setbluemoonfield(self, key, value):
        self.__quextMapping[value] = key

    def removequextfield(self, key):
        del self.__quextMapping[key]

    def removebluemoonfield(self, key):
        del self.__quextMapping.inverse[key]


class BiDirectionMapKeyError(Exception):
    def __init__(self, value):
        self.value = value
        msg = 'Key "{}" not found!'
        super().__init__(msg.format(value))


class BiDirectionMap(dict):
    def __init__(self, *args, **kwargs):
        super(BiDirectionMap, self).__init__(*args, **kwargs)
        self.inverse = collections.defaultdict()
        for key, value in self.items():
            self.inverse[value] = key

    def __setitem__(self, key, value):
        if key in self:
            self.inverse[self[key]].remove(key)
        super(BiDirectionMap, self).__setitem__(key, value)
        self.inverse[value] = key

    def __delitem__(self, key):
        if key not in self or self[key] not in self.inverse:
            raise BiDirectionMapKeyError(key)
        if self[key] in self.inverse:
            del self.inverse[self[key]]
        super(BiDirectionMap, self).__delitem__(key)


quext_to_bluemoon = {'a': 1,
                     'b': 2,
                     'c': 3,
                     'd': 4}

Test_BlueMoon_Data = {
    "addendum_access_gate": "quext_access_date",
    "addendum_additional_special_provisions": "",
    "addendum_affordable_housing": "",
    "addendum_animal_addendum": "",
    "addendum_apartment_rules": "",
    "addendum_asbestos": "",
    "addendum_bed_bug": "",
    "addendum_early_termination": "",
    "addendum_enclosed_garage": "",
    "addendum_intrusion_alarm": "",
    "addendum_inventory_and_condition": "",
    "addendum_lead_hazard_disclosure": "",
    "addendum_lease_contract_guaranty": "",
    "addendum_legal_description": "",
    "addendum_military_scra": "",
    "addendum_mold": "",
    "addendum_move_out_cleaning_instructions": "",
    "addendum_move_out_days_notice": 60,
    "addendum_notice_of_intent_to_move_out": "",
    "addendum_other1": "",
    "addendum_other1_description": "Fire Extinguisher",
    "addendum_other2": "",
    "addendum_other2_description": "Energyze",
    "addendum_other3": "",
    "addendum_other3_description": "",
    "addendum_other4": "",
    "addendum_other4_description": "",
    "addendum_parking_permit": "",
    "addendum_parking_permit_quantity": "",
    "addendum_rent_concession": "",
    "addendum_rent_concession_amount": "",
    "addendum_rent_concession_discounted_months": "",
    "addendum_rent_concession_monthly_discount": "",
    "addendum_rent_concession_one_time": "",
    "addendum_rent_concession_one_time_amount": "",
    "addendum_rent_concession_one_time_months": "",
    "addendum_rent_concession_special_provisions": "",
    "addendum_renters_insurance": "",
    "addendum_repair_request_form": "",
    "addendum_satellite_dish": "",
    "addendum_security_guidelines": "",
    "addendum_tceq_guide": "",
    "addendum_trash_removal_recycling_flat_fee": "10.00",
    "addendum_utility_allocation": "",
    "addendum_utility_allocation_cable_tv": "",
    "addendum_utility_allocation_central_system_costs": "",
    "addendum_utility_allocation_electricity": "",
    "addendum_utility_allocation_gas": "",
    "addendum_utility_allocation_services_govt_fees": "",
    "addendum_utility_allocation_stormwater_drainage": "",
    "addendum_utility_allocation_trash": "",
    "addendum_utility_allocation_water": "",
    "addendum_utility_submetering": "",
    "addendum_utility_submetering_electricity": "",
    "addendum_utility_submetering_gas": "",
    "addendum_utility_submetering_water": "",
    "additional_special_provisions": "",
    "address": "4139 Bellaire Blvd",
    "alarm_company_required_to_activate": "",
    "alarm_instructions_attached": "alarminstructionsonmovein",
    "alarm_maintainer": "",
    "alarm_permit_activation_contact": "",
    "alarm_permit_required_to_activate": "alarmpermitnotrequired",
    "alarm_repair_contact": "alarmfailurecontactyou",
    "alarm_repairs_paid_by": "alarmrepairpaidbyyou",
    "alarm_required": "alarmnotrequired",
    "alarm_required_company": "",
    "alarm_resident_chooses_company": "",
    "allocation_combo_percent": "",
    "allocation_square_foot_percent": "",
    "carport_cost_included_in_rent": "",
    "concession_addendum_attached_yes": "",
    "construction_special_provisions": "",
    "ctrl_sys_util_adden_alloc_basis": "",
    "ctrl_sys_util_adden_combo_formula_util": "",
    "ctrl_sys_util_adden_formula": "",
    "ctrl_sys_util_adden_heat_ac": "",
    "ctrl_sys_util_adden_hot_water": "",
    "ctrl_sys_util_adden_monthly_avg_basis": "",
    "ctrl_sys_util_adden_monthly_avg_hot_water": "",
    "ctrl_sys_util_adden_monthly_avg_hvac": "",
    "ctrl_sys_util_adden_submetered_formula_util": "",
    "date_of_lease": "2021-07-12T00:00:00+00:00",
    "days_prorated": 19,
    "days_required_for_notice_of_lease_termination": "60",
    "dryer_install": "",
    "early_termination_days_written_notice": 60,
    "early_termination_fee": "",
    "early_termination_fee_due_days_before_termination": "30",
    "early_termination_last_day_of_month": "termanyday",
    "early_termination_limited_to_fact": "termnotlimited",
    "early_termination_special_provisions": "",
    "electric_service_allocation_method": "",
    "electric_service_allocation_unit_square_feet_percent": "",
    "electric_service_average_bill": "",
    "electric_service_estimated_percent_use": "",
    "electric_service_reconnect_fee": "",
    "electric_transfer_fee": "50.00",
    "electronic_payment_addendum_resident_1_rent": "",
    "electronic_payment_addendum_resident_2_rent": "",
    "electronic_payment_addendum_resident_3_rent": "",
    "electronic_payment_addendum_resident_4_rent": "",
    "electronic_payment_addendum_resident_5_rent": "",
    "electronic_payment_addendum_resident_6_rent": "",
    "electronic_payment_addendum_special_provisions": "",
    "floor_plan": "",
    "garage_addendum_carport_provided": "",
    "garage_addendum_carport_space_no": "",
    "garage_addendum_garage_key": "",
    "garage_addendum_garage_opener": "",
    "garage_addendum_garage_or_carport_provided": "",
    "garage_addendum_garage_provided": "",
    "garage_addendum_garage_space_no": "",
    "garage_addendum_opener_fine": "",
    "garage_addendum_opener_will_be_provided": "",
    "garage_addendum_storage_unit_no": "",
    "garage_addendum_storage_unit_provided": "",
    "garage_cost_included_in_rent": "",
    "gas_allocation_administrative_fee": "",
    "gas_allocation_deduction_percent": "",
    "gas_allocation_formula": "",
    "gas_allocation_late_fee": "",
    "guarantor_last_date_for_renewal": "",
    "guarantor_length_of_obligations": "",
    "gun_no_conceal_area": "",
    "gun_no_conceal_office": "",
    "gun_no_conceal_property": "",
    "gun_no_conceal_rooms": "",
    "gun_no_open_carry_area": "",
    "gun_no_open_carry_office": "",
    "gun_no_open_carry_property": "",
    "gun_no_open_carry_rooms": "",
    "inventory_move_in": "",
    "inventory_move_in_date": "",
    "inventory_move_out": "",
    "inventory_move_out_date": "",
    "late_charge_daily_cannot_exceed_days": "",
    "late_charge_daily_charge": "",
    "late_charge_daily_percent_of_rent": "",
    "late_charge_dollar_amount": "",
    "late_charge_initial_charge": "",
    "late_charge_percent_of_rent": "",
    "late_charge_percentage_of_rent": "10",
    "lead_based_paint_knowledge": "",
    "lead_based_paint_knowledge_comments": "",
    "lead_based_paint_reports": "",
    "lead_based_paint_reports_comments": "",
    "lease_begin_date": "2021-07-12T00:00:00+00:00",
    "lease_end_date": "2022-07-31T00:00:00+00:00",
    "lease_renewal_changed_terms": "",
    "lease_renewal_other_attachments": "",
    "lease_renewal_other_charges": "",
    "lease_renewal_representation": "",
    "lease_terminates_last_day_of_month": "onexact",
    "legal_description_of_unit": "RES A BLK 1, RESERVE AT CITY CENTRE",
    "locator_address": "",
    "locator_city_state_zip": "",
    "locator_name": "",
    "locator_phone": "",
    "maximum_guest_stay": 3,
    "monthly_pest_control_rent": "2.00",
    "monthly_trash_rent": "10.00",
    "move_out_request": "",
    "no_smoking_addendum_smoking_areas": "",
    "no_smoking_addendum_smoking_distance": "",
    "no_smoking_addendum_smoking_permitted_balcony": "",
    "no_smoking_addendum_smoking_permitted_outside": "",
    "no_smoking_addendum_smoking_policy": "smokingallowed",
    "number_of_apartment_keys": "",
    "number_of_mail_keys": "",
    "number_of_other_keys": "",
    "occupant_1": "",
    "occupant_2": "",
    "occupant_3": "",
    "occupant_4": "",
    "old_lease_begin_date": "",
    "old_lease_end_date": "",
    "old_resident": "",
    "old_resident_1": "",
    "old_resident_2": "",
    "old_resident_3": "",
    "old_resident_4": "",
    "old_resident_5": "",
    "old_resident_6": "",
    "old_unit_number": "",
    "other_cost_included_in_rent": "",
    "other_cost_included_in_rent_desc": "",
    "other_key_type": "remote(s)",
    "owners_representative_address_1": "811 Town & Country Blvd.",
    "owners_representative_address_2": "Houston, TX 77024",
    "owners_representative_after_hours_phone": "(713)463-0400",
    "owners_representative_fax": "(713)463-0401",
    "owners_representative_telephone": "(713)463-0400",
    "party_obligated_to_fertilize": "",
    "party_responsible_for_lawn_mowing": "",
    "party_responsible_for_lawn_trash": "",
    "party_responsible_for_lawn_watering": "",
    "pay_electric_to_representative": "elec2",
    "pay_plan_amount_1": "",
    "pay_plan_amount_10": "",
    "pay_plan_amount_11": "",
    "pay_plan_amount_12": "",
    "pay_plan_amount_2": "",
    "pay_plan_amount_3": "",
    "pay_plan_amount_4": "",
    "pay_plan_amount_5": "",
    "pay_plan_amount_6": "",
    "pay_plan_amount_7": "",
    "pay_plan_amount_8": "",
    "pay_plan_amount_9": "",
    "pay_plan_due_current_month": "",
    "pay_plan_due_date_1": "",
    "pay_plan_due_date_10": "",
    "pay_plan_due_date_11": "",
    "pay_plan_due_date_12": "",
    "pay_plan_due_date_2": "",
    "pay_plan_due_date_3": "",
    "pay_plan_due_date_4": "",
    "pay_plan_due_date_5": "",
    "pay_plan_due_date_6": "",
    "pay_plan_due_date_7": "",
    "pay_plan_due_date_8": "",
    "pay_plan_due_date_9": "",
    "pay_plan_due_next_month": "",
    "pay_plan_due_time_period": "",
    "pay_plan_due_time_period_description": "",
    "pay_plan_lease_signed_date": "",
    "pay_plan_lease_signed_year": "",
    "pay_rent_address": "drop box",
    "pay_rent_at_online_site": "",
    "pay_rent_at_other_location": "",
    "pay_rent_on_site": "",
    "per_person_bedroom_sharing": "",
    "per_person_max_sharing_common_areas": "",
    "per_person_transfer_fee": "",
    "pet_2_age": "",
    "pet_2_breed": "",
    "pet_2_color": "",
    "pet_2_date_of_last_shots": "",
    "pet_2_house_broken": "",
    "pet_2_license_city": "",
    "pet_2_license_number": "",
    "pet_2_name": "",
    "pet_2_owners_name": "",
    "pet_2_type": "",
    "pet_2_weight": "",
    "pet_3_age": "",
    "pet_3_breed": "",
    "pet_3_color": "",
    "pet_3_date_of_last_shots": "",
    "pet_3_house_broken": "",
    "pet_3_license_city": "",
    "pet_3_license_number": "",
    "pet_3_name": "",
    "pet_3_owners_name": "",
    "pet_3_type": "",
    "pet_3_weight": "",
    "pet_additional_rent": "20.00",
    "pet_age": "",
    "pet_breed": "",
    "pet_charge_daily_charge": "10.00",
    "pet_charge_initial_charge": "100.00",
    "pet_color": "",
    "pet_date_of_last_shots": "",
    "pet_dr_address": "",
    "pet_dr_city": "",
    "pet_dr_name": "",
    "pet_dr_telephone": "",
    "pet_house_broken": "",
    "pet_license_city": "",
    "pet_license_number": "",
    "pet_name": "",
    "pet_one_time_fee": "400.00",
    "pet_owners_name": "",
    "pet_security_deposit": "",
    "pet_special_provisions": "",
    "pet_type": "",
    "pet_urinate_inside_areas": "",
    "pet_urinate_outside_areas": "",
    "pet_weight": "",
    "prorated_rent": "627",
    "prorated_rent_due_date": "",
    "prorated_rent_due_first_month": "firstmo",
    "prorated_rent_per_day": "33",
    "reletting_charge": "",
    "reletting_charge_percent": 85,
    "remote_card_code_addendum_add_card_fee": "",
    "remote_card_code_addendum_add_remote_fee": "150.00",
    "remote_card_code_addendum_card": "",
    "remote_card_code_addendum_code": "",
    "remote_card_code_addendum_code_change": "",
    "remote_card_code_addendum_lost_card": "",
    "remote_card_code_addendum_lost_card_deduct": "",
    "remote_card_code_addendum_lost_remote": "",
    "remote_card_code_addendum_lost_remote_deduct": "150.00",
    "remote_card_code_addendum_remote": "",
    "remote_card_code_addendum_replace_card_fee": "",
    "remote_card_code_addendum_replace_remote_fee": "150.00",
    "rent": "1000",
    "rent_due_date": "4",
    "rent_installments_number": "",
    "renters_insurance_default_fee": "",
    "renters_insurance_election": "insuranceother",
    "renters_insurance_election_payment": "",
    "renters_insurance_liability_limit": "100000.00",
    "renters_insurance_provider": "",
    "renters_insurance_requirement": "insurancerequired",
    "resident_1": "John Smith",
    "resident_2": "",
    "resident_3": "",
    "resident_4": "",
    "resident_5": "",
    "resident_6": "",
    "returned_check_charge": "85.00",
    "roommate_amendment_special_provisions": "",
    "satellite_addendum_insurance": "300000.00",
    "satellite_addendum_no_dishes": 1,
    "satellite_addendum_security_deposit": "",
    "satellite_addendum_security_deposit_days": "1",
    "satellite_addendum_security_deposit_effective": "satelliteafterinstall",
    "security_deposit": "",
    "security_deposit_includes_animal_deposit": "",
    "security_deposit_refund_check_payable": "depositcheckissuedjointly",
    "security_deposit_refund_one_check_mailed_to": "",
    "services_govt_fees_addendum_administrative_fee": "",
    "services_govt_fees_addendum_bill_based_on": "",
    "services_govt_fees_addendum_cable_satellite": "",
    "services_govt_fees_addendum_conservation_district": "",
    "services_govt_fees_addendum_emergency_services": "",
    "services_govt_fees_addendum_inspection": "",
    "services_govt_fees_addendum_late_fee": "",
    "services_govt_fees_addendum_other_1": "",
    "services_govt_fees_addendum_other_1_desc": "Pest Control $2",
    "services_govt_fees_addendum_other_2": "",
    "services_govt_fees_addendum_other_2_desc": "",
    "services_govt_fees_addendum_other_3": "",
    "services_govt_fees_addendum_other_3_desc": "",
    "services_govt_fees_addendum_other_4": "",
    "services_govt_fees_addendum_other_4_desc": "",
    "services_govt_fees_addendum_other_5": "",
    "services_govt_fees_addendum_other_5_desc": "",
    "services_govt_fees_addendum_other_6": "",
    "services_govt_fees_addendum_other_6_desc": "",
    "services_govt_fees_addendum_registration_license": "",
    "services_govt_fees_addendum_stormwater_drainage": "",
    "services_govt_fees_addendum_street_repair": "",
    "services_govt_fees_addendum_trash": "",
    "short_lease_special_provisions": "",
    "special_provisions": "In addition to monthly charges for Trash, Pest &/or Gas, residents will be charged for monthly Administrative fees as defined in the attached addenda, a monthly amenity fee of $20.00.",
    "storage_cost_included_in_rent": "",
    "stormwater_addendum_administrative_fee": "1.00",
    "stormwater_addendum_bill_based_on": "stormwaterallocationperunit",
    "student_housing_special_provisions": "",
    "student_lease_apartment": "",
    "student_lease_bedroom_change_transfer_fee": "",
    "student_lease_bedroom_number": "",
    "student_lease_floor_plan": "",
    "student_lease_monthly_installment": "",
    "student_lease_total_lease_term_rent": "",
    "student_lease_unit_transfer_fee": "",
    "submeter_average_monthly_bill": "12.12",
    "submeter_highest_monthly_bill": "68.85",
    "submeter_lowest_monthly_bill": "1.22",
    "submeter_water_consumption_from_date": "1",
    "submeter_water_consumption_to_date": "31",
    "submeter_water_service_fee": 9,
    "tceq_water_allocation_method": "",
    "trash_addendum_administrative_fee": "2.95",
    "trash_addendum_administrative_fee_flat": "2.95",
    "trash_addendum_bill_based_on": "trashallocationother",
    "trash_addendum_bill_late_fee": "",
    "trash_addendum_flat_late_fee": "",
    "unit_furnished": "",
    "unit_number": "",
    "utilities_cable_tv": "",
    "utilities_electricity": "",
    "utilities_gas": "",
    "utilities_government_fees": "",
    "utilities_internet": "",
    "utilities_master_antenna": "",
    "utilities_other": "",
    "utilities_other_description": "",
    "utilities_stormwater_drainage": "",
    "utilities_trash": "",
    "utilities_wastewater": "",
    "utilities_water": "",
    "virus_waiver_signed_date": "",
    "virus_waiver_signed_year": "",
    "waiver_email_contact": "",
    "waiver_period_end_date": "",
    "waiver_period_rent_due_date": "",
    "waiver_period_start_date": "",
    "waiver_phone_contact": "",
    "washer_dryer_cost_included_in_rent": "",
    "washer_install": "",
    "water_allocation_bill_date": ""
}
