constants = {
  "RESIDENT_ID": "tu-residentid ",
  "HTTP_GOOD_RESPONSE_CODE": 200,
  "HTTP_BAD_REQUEST_CODE": 400,
  "HTTP_NOT_FOUND_CODE": 404,
  "HTTP_ERROR_CODE": 404,
  "BACKGROUND_SCREENING_MAX_ITERATIONS": 10
}