class EntrataConstants:
    FROM_DATE = "fromDate"
    TO_DATE = "toDate"
    QUEXT_DATE_FORMAT = '%Y-%m-%d'
    ENTRATA_DATE_FORMAT = '%m/%d/%Y'
    ENTRATA_TIMEZONE = 'MST'
    QUEXT_TIMEZONE = 'GMT'
    AVAILABLE_HOURS = "availableHours"
    AVAILABLE_HOUR = "availableHour"
    DATE = "date"
    START_TIME = "startTime"
    END_TIME = "endTime"
    DATETIME_FORMAT = '%m/%d/%Y %H:%M:%S'
    GET_CALENDAR_AVAILABILITY = "getCalendarAvailability"
    SUCCESS = "success"
    RESPONSE = "response"
    RESULT = "result"
    PROPERTYID = "propertyId"
    PROPERTY_CALENDAR_AVAILABILITY = "propertyCalendarAvailability"
    GUESTCARD_METHOD = 'Online Guest Card'
    SENDLEADS = "sendLeads"
    GUESTCARD_ID = 10
    BOOK_TOUR_EVENT = 'SelfGuidedTour'
    EVENT_REASON_ID = "118567"
    PHONE = 'phone'
    EMAIL = "email"
