class ResmanConstants:
    DATA = "data"
    HEADERS = {'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'application/json'}
    URLHEADERS = {"Content-type": "application/x-www-form-urlencoded"}
    PROPERTIES = 'Properties'
    UNITS = 'Units'
    PROPERTY_ID = 'PropertyId'
    FOREIGN_COMMUNITY_ID = 'foreign_community_id'
    PLATFORM = 'platform'
    RESIDENTS_INTERFACE = "Leasing"
    RESIDENTS_METHOD = "GetCurrentResidents"
    UNITS_INTERFACE = "Property"
    UNITS_METHOD = "GetUnits"
    LEASING_INTERFACE = "Leasing"
    LEASING_METHOD = "GetApplicantsAndCurrentResidents"
    AVAILABILITY_PRICING_INTERFACE = "MITS"
    AVAILABILITY_PRICING_METHOD = "GetMarketing4_0"
    RESMAN_EXTERNAL = "ResMan (External)"
    APARTMENT = "apartment"
    INCLUDECONCESSIONSINLEASETERMPRICING = 'includeConcessionsInLeaseTermPricing'
    VACANT = "vacant"
    INCLEASEHISTORY = "IncludeLeaseHistory"
    PENDING_RENEWAL = "Pending Renewal"
    GUESTCARD = 'guestCards'
    GETPROSPECTSOURCES = 'GetProspectSources'
    MITS = "MITS"
    POST_LEAD_MANAGEMENT = "PostLeadManagement4_0"
    SEARCH_PROSPECT = '[Resman] Search Prospects'
    POST_LEAD_MANAGEMENT_REST = '[Resman] Post Lead Management 4_0'
    DH = "DH"
    WS = "WS"
    
    # UNIT AVAILABILITY AND PRICING CONSTANT
    NAME = "Name"
    MITS_OFFERTERM = "MITS_OfferTerm"
    EFFECTIVERENT = "EffectiveRent"
    TERM = "Term"
    STARTDATE ="StartDate"
    ENDDATE = "EndDate"
    MARKETINGNAME="MarketingName"
    UNITTYPE = "UnitType"
    UNITBEDROOMS = "UnitBedrooms"
    UNITBATHROOMS = "UnitBathrooms"
    UNITECONOMICSTATUS = "UnitEconomicStatus"
    UNITOCCUPANCYSTATUS = "UnitOccupancyStatus"
    UNITLEASEDSTATUS = "UnitLeasedStatus"
    FLOORPLANNAME = "FloorplanName"
    BUILDINGNAME = "BuildingName"
    ADDRESS = "Address"
    FLOORLEVEL = "FloorLevel"
    PRICING = "Pricing"
    FLOORPLAN = "Floorplan"
    CONTENTTYPE = "text"
    SOURCESYSTEM = "ResMan"
    AVAILABLE = "available"
    FILTER_ON_AVAILABILITY = "filter_on_availability"

    # GUESTCARD CONSTANTS
    XML = "Xml"
    LEAD_MANAGEMENT = "LeadManagement"
    PROSPECTS = "Prospects"
    PROSPECT = "Prospect"
    EVENTS = "Events"
    EVENT = "Event"
    TRANSACTION_SOURCE = "TransactionSource"
    EVENTDATE = "@EventDate"
    COMMENTS = "Comments"
    INTEGRATION_PARTNER_ID = "IntegrationPartnerID"
    API_KEY = "ApiKey"
    ACCOUNT_ID = "AccountID"
    QUEXT = "Quext"
    STATUS = "Status"
    SUCCESS = "Success"
    EMAIL = "Email"
    CUSTOMERS = "Customers"
    CUSTOMER = "Customer"
    PHONE = "Phone"
    FIRST_CONTACT = "FirstContact"
    B = "B"
    RESPONSE = "Response"
    FOREIGNCUSTOMERID = "foreign_customer_id"
    SOURCE = "source"
    WALKIN = "WalkIn"
    TRUE = "true"
    PHONENUMBER = "PhoneNumber"
    APPOINTMENT_ID = "appointment_id"
    CUSTOMER_PREFERENCES = 'CustomerPreferences'
    IDENTIFICATION = "Identification"
    IDVALUE = "@IDValue"
    AVAILABLETIMES = "availableTimes"
    ERROR = 'error'
    MESSAGE = 'message'